const definitions=[
  {id:"pkp-plk-realtime",name:"PKP PLK Open Rail Data",url:"PKP_PLK_API_URL",token:"PKP_PLK_API_KEY",country:"PL",enabled:true},
  {id:"zsr-realtime",name:"ŽSR Train Movement",url:"ZSR_RAIL_API_URL",country:"SK",enabled:true},
  {id:"mav-emma",name:"MÁV EMMA",url:"MAV_RAIL_API_URL",country:"HU",enabled:true},
  {id:"rne-tis",name:"RailNetEurope TIS",url:"RNE_TIS_API_URL",token:"RNE_TIS_TOKEN",country:"EU",enabled:false},
  {id:"contract-rail-feed",name:"Contractual rail logistics feed",url:"CONTRACT_RAIL_API_URL",token:"CONTRACT_RAIL_API_TOKEN",country:null,enabled:false},
];

const normalizeRecord=(record,source)=>({trainNumber:String(record.trainNumber||record.train_number||record.number||"").replace(/^№\s*/,""),serviceDate:String(record.serviceDate||record.operatingDate||record.date||new Date().toISOString()).slice(0,10),origin:record.origin||record.from||null,destination:record.destination||record.to||null,route:record.route||[record.origin||record.from,record.destination||record.to].filter(Boolean).join(" — "),reportedStation:record.station||record.lastStation||null,updatedAt:record.observedAt||record.updatedAt||new Date().toISOString(),delayMinutes:Number.isFinite(Number(record.delayMinutes))?Number(record.delayMinutes):null,sourceId:source.id,sourceEvidence:"authorized-cross-border-feed",positionEvidence:record.station||record.lastStation?"reported-station-passage":"none",publicStatus:record.status||"cross-border observation"});

export async function collectInternationalRailSources(env=process.env){const updates=[],statuses=[];for(const source of definitions){const endpoint=String(env[source.url]||"").trim(),token=source.token?String(env[source.token]||"").trim():"";if(!source.enabled||!endpoint||(source.token&&!token)){statuses.push({sourceId:source.id,status:"requires_configuration",checkedAt:new Date().toISOString(),error:null,recordsCount:0});continue;}try{const response=await fetch(endpoint,{headers:{Accept:"application/json",...(token?{Authorization:`Bearer ${token}`,"X-API-Key":token}:{})},signal:AbortSignal.timeout(20_000)});if(!response.ok)throw new Error(`HTTP ${response.status}`);const payload=await response.json(),records=Array.isArray(payload)?payload:Array.isArray(payload.records)?payload.records:Array.isArray(payload.operations)?payload.operations:[];const accepted=records.map((record)=>normalizeRecord(record,source)).filter((item)=>item.trainNumber&&item.route&&(!item.serviceDate||/^\d{4}-\d{2}-\d{2}$/.test(item.serviceDate)));updates.push(...accepted);statuses.push({sourceId:source.id,status:"online",checkedAt:new Date().toISOString(),recordsCount:accepted.length,error:null});}catch(error){statuses.push({sourceId:source.id,status:"unavailable",checkedAt:new Date().toISOString(),recordsCount:0,error:String(error?.message||error).slice(0,300)});}}const sources=Object.fromEntries(statuses.map((item)=>[item.sourceId,{status:{status:item.status,checkedAt:item.checkedAt,error:item.error||null,label:`${item.sourceId}: ${item.status}`},recordsCount:item.recordsCount||0,updates:[]} ]));return {updates,statuses,sources};}

export const internationalRailSourceDefinitions=definitions.map(({url,token,...item})=>({...item,requiredSecrets:[url,token].filter(Boolean)}));
