import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
const sqlite = await import("node:sqlite").catch(() => null);

test("D1 migration creates the event backend schema", {
  skip: sqlite ? false : "node:sqlite is unavailable on this supported Node version",
}, async () => {
  const sql = await readFile(new URL("../backend/migrations/0001_initial.sql", import.meta.url), "utf8");
  const historySql = await readFile(new URL("../backend/migrations/0003_run_history.sql", import.meta.url), "utf8");
  const database = new sqlite.DatabaseSync(":memory:");
  const observabilitySql = await readFile(new URL("../backend/migrations/0004_model_observability.sql", import.meta.url), "utf8");
  const fuelSql = await readFile(new URL("../backend/migrations/0005_fuel_platform.sql", import.meta.url), "utf8");
  const incidentSql = await readFile(new URL("../backend/migrations/0008_fuel_incidents.sql", import.meta.url), "utf8");
  const freightSql = await readFile(new URL("../backend/migrations/0009_freight_intelligence.sql", import.meta.url), "utf8");
  const secureCoreSql = await readFile(new URL("../backend/migrations/0010_secure_core.sql", import.meta.url), "utf8");
  const intelligencePlatformSql = await readFile(new URL("../backend/migrations/0011_intelligence_platform.sql", import.meta.url), "utf8");
  const corridorNodesSql = await readFile(new URL("../backend/migrations/0012_international_corridor_nodes.sql", import.meta.url), "utf8");
  const railV2Sql = await readFile(new URL("../backend/migrations/0013_rail_intelligence_v2.sql", import.meta.url), "utf8");
  const railGraphSql = await readFile(new URL("../backend/migrations/0014_rail_graph_registry.sql", import.meta.url), "utf8");
  const routingSql = await readFile(new URL("../backend/migrations/0015_rail_intelligence_routing.sql", import.meta.url), "utf8");
  const foundationFusionSql = await readFile(new URL("../backend/migrations/0016_rail_foundation_fusion.sql", import.meta.url), "utf8");
  const railV3Sql = await readFile(new URL("../backend/migrations/0017_rail_intelligence_v3.sql", import.meta.url), "utf8");
  const fusionV2Sql = await readFile(new URL("../backend/migrations/0018_observation_fusion_v2.sql", import.meta.url), "utf8");
  database.exec(historySql);
  database.exec(sql);
  database.exec(observabilitySql);
  database.exec(fuelSql);
  database.exec(incidentSql);
  database.exec(freightSql);
  database.exec(secureCoreSql);
  database.exec(intelligencePlatformSql);
  database.exec(corridorNodesSql);
  database.exec(railV2Sql);
  database.exec(railGraphSql);
  database.exec(routingSql);
  database.exec(foundationFusionSql);
  database.prepare("INSERT INTO model_evaluations(evaluation_id,run_id,train_number,from_station_id,to_station_id,predicted_minutes,actual_minutes,absolute_error_minutes,within_p80,baseline_samples,evaluated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run("replay:legacy","run-a","1","a","b",10,11,1,1,1,"2026-07-28T10:00:00Z");
  database.prepare("INSERT INTO model_evaluations(evaluation_id,run_id,train_number,from_station_id,to_station_id,predicted_minutes,actual_minutes,absolute_error_minutes,within_p80,baseline_samples,evaluated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run("twin:legacy","run-b","2","a","b",10,12,2,0,1,"2026-07-28T10:00:00Z");
  database.exec(railV3Sql);
  database.exec(fusionV2Sql);
  const tables = database.prepare("SELECT name FROM sqlite_master WHERE type='table' ORDER BY name").all().map((row) => row.name);
  assert.ok(tables.includes("runs"));
  assert.ok(tables.includes("events"));
  assert.ok(tables.includes("source_health"));
  assert.ok(tables.includes("run_snapshots"));
  assert.ok(tables.includes("segment_stats"));
  assert.ok(tables.includes("model_evaluations"));
  assert.ok(tables.includes("source_health_checks"));
  assert.ok(tables.includes("fuel_stations"));
  assert.ok(tables.includes("fuel_current_state"));
  assert.ok(tables.includes("fuel_moderation_queue"));
  assert.ok(tables.includes("fuel_incident_signals"));
  assert.ok(tables.includes("freight_observations"));
  assert.ok(tables.includes("freight_source_health"));
  assert.ok(tables.includes("access_users"));
  assert.ok(tables.includes("access_sessions"));
  assert.ok(tables.includes("feature_flags"));
  assert.ok(tables.includes("restricted_evidence"));
  assert.ok(tables.includes("secure_audit"));
  assert.ok(tables.includes("rail_nodes"));
  assert.ok(tables.includes("rail_edges"));
  assert.ok(tables.includes("rail_observations"));
  assert.ok(tables.includes("twin_predictions"));
  assert.ok(tables.includes("trajectory_points"));
  assert.ok(tables.includes("ops_movements"));
  assert.ok(tables.includes("ops_workflows"));
  assert.ok(tables.includes("ops_notifications"));
  assert.ok(tables.includes("node_activity_scores"));
  assert.ok(tables.includes("network_anomalies"));
  assert.ok(tables.includes("international_corridors"));
  assert.ok(tables.includes("intelligence_cycles"));
  assert.ok(tables.includes("rail_graph_versions"));
  assert.ok(tables.includes("station_registry"));
  assert.ok(tables.includes("station_aliases"));
  assert.ok(tables.includes("rail_segment_geometries"));
  assert.ok(tables.includes("rail_route_cache"));
  assert.ok(tables.includes("observation_run_links"));
  assert.ok(tables.includes("model_calibration_profiles"));
  assert.ok(tables.includes("rail_graph_diagnostics"));
  assert.ok(tables.includes("station_codes"));
  assert.ok(tables.includes("observation_link_candidates"));
  assert.ok(tables.includes("twin_state_transitions"));
  assert.ok(tables.includes("model_calibration_profiles_v3"));
  assert.ok(tables.includes("expected_train_runs"));
  assert.ok(tables.includes("rail_coverage_gaps"));
  assert.ok(tables.includes("observation_fusion_groups"));
  assert.ok(tables.includes("external_rail_sources"));
  assert.equal(database.prepare("SELECT evaluation_kind FROM model_evaluations WHERE evaluation_id='replay:legacy'").get().evaluation_kind,"replay");
  assert.equal(database.prepare("SELECT evaluation_kind FROM model_evaluations WHERE evaluation_id='twin:legacy'").get().evaluation_kind,"prospective");
  const corridors=database.prepare("SELECT corridor_id,border_nodes_json FROM international_corridors ORDER BY corridor_id").all();
  assert.equal(corridors.length,5);
  assert.ok(corridors.every((item)=>JSON.parse(item.border_nodes_json).length>0));
  database.close();
});

