import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { DatabaseSync } from "node:sqlite";
import { handleIntelligencePlatformRequest } from "../backend/src/intelligence/api.js";

class Statement{constructor(database,sql){this.database=database;this.sql=sql;this.values=[];}bind(...values){this.values=values;return this;}all(){return{results:this.database.prepare(this.sql).all(...this.values)};}first(){return this.database.prepare(this.sql).get(...this.values)||null;}run(){return this.database.prepare(this.sql).run(...this.values);}}
class D1Adapter{constructor(database){this.database=database;}prepare(sql){return new Statement(this.database,sql);}async batch(statements){return statements.map(statement=>statement.run());}}

test("restricted Operations Hub returns probabilistic freight corridors and station facts",async()=>{
  const database=new DatabaseSync(":memory:");
  for(const file of ["0001_initial.sql","0004_model_observability.sql","0010_secure_core.sql","0011_intelligence_platform.sql","0013_rail_intelligence_v2.sql","0014_rail_graph_registry.sql","0015_rail_intelligence_routing.sql","0016_rail_foundation_fusion.sql","0017_rail_intelligence_v3.sql","0018_observation_fusion_v2.sql","0020_observation_fusion_v3.sql","0021_operations_hub_v2.sql"])database.exec(await readFile(new URL(`../backend/migrations/${file}`,import.meta.url),"utf8"));
  const now=new Date().toISOString();
  database.prepare("INSERT INTO restricted_evidence(evidence_id,domain,source_id,occurred_at,received_at,evidence_excerpt,classification_json,corridor_code,confidence,sensitivity_level,review_status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)").run("e-1","rail_freight","freight-tg-test",now,now,"Вантажний поїзд на станції Коростень",JSON.stringify({freightType:"bulk",station:"Коростень",direction:"київ",locomotive:"ВЛ80Т-1445",entityKey:"locomotive:ВЛ80Т-1445",entityConfidence:.92}),"kyiv-korosten",.55,"restricted","pending",now,now);
  const response=await handleIntelligencePlatformRequest(new Request("https://example.test/api/restricted/operations-hub"),{DB:new D1Adapter(database)},{permissions:["*"]},(value,status=200)=>new Response(JSON.stringify(value),{status,headers:{"Content-Type":"application/json"}}));
  assert.equal(response.status,200);
  const body=await response.json();
  assert.equal(body.freightCorridors.length,1);
  assert.equal(body.freightStationFacts[0].station,"Коростень");
  assert.equal(body.freightTracks.length,1);
  assert.equal(body.freightTracks[0].linkedMovementId,null);
  assert.equal(body.freightPolicy.exactFreightPositions,false);
  database.prepare("INSERT INTO runs(run_id,train_number,service_date,route,origin,destination,current_update_json,first_observed_at,last_observed_at) VALUES(?,?,?,?,?,?,?,?,?)").run("run-ops","6366","2026-07-27","Гребінка — Ромодан","Гребінка","Ромодан","{}",now,now);
  database.prepare("INSERT INTO ops_movements(movement_id,run_id,train_number,last_observed_at,confidence,position_status) VALUES(?,?,?,?,?,?)").run("run-ops","run-ops","6366",now,.3,"estimated");
  const factResponse=await handleIntelligencePlatformRequest(new Request("https://example.test/api/restricted/rail-intelligence",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({runId:"run-ops",trainNumber:"6366",station:"Гребінка",observedAt:now,reliability:.82,note:"operator check"})}),{DB:new D1Adapter(database)},{id:"admin-1",role:"administrator",permissions:["*"]},(value,status=200)=>new Response(JSON.stringify(value),{status,headers:{"Content-Type":"application/json"}}));
  assert.equal(factResponse.status,201); assert.equal(database.prepare("SELECT source_id FROM events WHERE run_id='run-ops'").get().source_id,"operations-hub"); const movement=database.prepare("SELECT last_station,position_status,confidence FROM ops_movements WHERE run_id='run-ops'").get(); assert.equal(movement.last_station,"Гребінка"); assert.equal(movement.position_status,"reported"); assert.equal(movement.confidence,.82); assert.equal(database.prepare("SELECT COUNT(*) total FROM secure_audit WHERE action='rail.observation_created'").get().total,1); assert.equal(database.prepare("SELECT COUNT(*) total FROM twin_recalculation_queue WHERE run_id='run-ops' AND processed_at IS NULL").get().total,1);
  database.prepare("INSERT INTO runs(run_id,train_number,service_date,route,origin,destination,current_update_json,first_observed_at,last_observed_at) VALUES(?,?,?,?,?,?,?,?,?)").run("run-alt","6366","2026-07-27","Гребінка — Київ","Гребінка","Київ","{}",now,now);
  database.prepare("INSERT INTO events(event_id,run_id,event_type,event_value_json,station,occurred_at,observed_at,source_id,authority,reliability,position_evidence,raw_update_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)").run("event-link","run-ops","station_report","{}","Гребінка",now,now,"test","public",.7,"station","{}");
  database.prepare("INSERT INTO observation_run_links(event_id,original_run_id,status,confidence,method,candidates_json,reason_json,updated_at,review_reason) VALUES(?,?,?,?,?,?,?,?,?)").run("event-link","run-ops","pending",.7,"entity-resolution-v2",JSON.stringify([{runId:"run-alt",probability:.55,features:[{label:"Совпадает номер",matched:true,weight:.42}]}]),"{}",now,"candidate-conflict");
  database.prepare("INSERT INTO observation_link_candidates(event_id,run_id,rank,score,probability,feature_json,created_at) VALUES(?,?,?,?,?,?,?)").run("event-link","run-alt",1,.73,.55,"[]",now);
  const queueResponse=await handleIntelligencePlatformRequest(new Request("https://example.test/api/restricted/rail-intelligence"),{DB:new D1Adapter(database)},{id:"admin-1",permissions:["*"]},(value,status=200)=>new Response(JSON.stringify(value),{status,headers:{"Content-Type":"application/json"}}));const queueBody=await queueResponse.json();assert.equal(queueBody.entityResolution.pending[0].candidates[0].runId,"run-alt");assert.equal(queueBody.observationFusion.method,"observation-fusion-v3");assert.equal(queueBody.entityResolution.method,"entity-resolution-v3");assert.ok(Array.isArray(queueBody.stationCoveragePriorities));
  const resolutionResponse=await handleIntelligencePlatformRequest(new Request("https://example.test/api/restricted/rail-intelligence",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"resolve-observation-link",eventId:"event-link",decision:"link",runId:"run-alt"})}),{DB:new D1Adapter(database)},{id:"admin-1",role:"administrator",permissions:["*"]},(value,status=200)=>new Response(JSON.stringify(value),{status,headers:{"Content-Type":"application/json"}}));assert.equal(resolutionResponse.status,200);const resolvedLink=database.prepare("SELECT canonical_run_id,status,decision_source FROM observation_run_links WHERE event_id='event-link'").get();assert.equal(resolvedLink.canonical_run_id,"run-alt");assert.equal(resolvedLink.status,"linked");assert.equal(resolvedLink.decision_source,"operator");
  database.prepare("INSERT INTO rail_graph_versions(version_id,source,checksum,status,station_count,segment_count,imported_stations,imported_segments,created_at,activated_at) VALUES(?,?,?,?,?,?,?,?,?,?)").run("graph-v1","OpenStreetMap","checksum","active",4314,13444,4314,13444,now,now);
  database.prepare("INSERT INTO rail_graph_import_state(version_id,next_station_chunk,next_segment_chunk,last_attempt_at,finished_at) VALUES(?,?,?,?,?)").run("graph-v1",35,108,now,now);
  const graphResponse=await handleIntelligencePlatformRequest(new Request("https://example.test/api/restricted/rail-intelligence"),{DB:new D1Adapter(database)},{permissions:["*"]},(value,status=200)=>new Response(JSON.stringify(value),{status,headers:{"Content-Type":"application/json"}}));
  assert.equal(graphResponse.status,200); const graphBody=await graphResponse.json(); assert.equal(graphBody.graphReference.versionId,"graph-v1"); assert.equal(graphBody.graphReference.status,"active"); assert.equal(graphBody.graphReference.stations,4314); assert.equal(graphBody.policy.model,"station-graph-probabilistic-twin-v4"); assert.ok(graphBody.policy.operationalStates.includes("approaching"));
  database.prepare("INSERT INTO model_evaluations(evaluation_id,run_id,train_number,from_station_id,to_station_id,predicted_minutes,actual_minutes,absolute_error_minutes,within_p80,baseline_samples,evaluated_at,source_id,evaluation_kind,model_version) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)").run("live-quality","run-ops","6366","hrebinka","romodan",40,44,4,1,10,now,"uz-live","prospective","rail-intelligence-v3");
  const analyticsResponse=await handleIntelligencePlatformRequest(new Request("https://example.test/api/restricted/analytics-network"),{DB:new D1Adapter(database)},{permissions:["*"]},(value,status=200)=>new Response(JSON.stringify(value),{status,headers:{"Content-Type":"application/json"}})); const analyticsBody=await analyticsResponse.json(); assert.equal(analyticsBody.calibration.modelVersion,"rail-intelligence-v4"); assert.equal(analyticsBody.calibration.prospectiveEvaluations,1);
  database.close();
});
